name: elasticgraph App Build

on:
  push:
    branches:
    - feat-elasticgraph

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: feat-elasticgraph
        submodules: 'true'

    - name: Checkout
      uses: actions/checkout@v3
      run: |
        pwd && ls && ls elasticgraph/ && du -sch elasticgraph/
                
    - name: Npm install
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
    - run: npm install
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: Dockerfile
        tags: adminmindgrep/gs_service:elasticgraph

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'adminmindgrep/gs_service:elasticgraph'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'LOW,MEDIUM,CRITICAL,HIGH'          